---
- name: "Ensure curl and git are installed"
  package:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - "curl"
      - "git"

- block:
    - name: "Clone vzdump2influx repository"
      git:
        repo: "{{ vzdump2influx_repository_url }}"
        dest: "{{ vzdump2influx_repository_directory }}"
        version: "{{ vzdump2influx_version }}"
        update: true
        force: false

  rescue:
    - name: "No update"
      debug:
        msg: "Repository has not been updated"

- name: "Make vzdump2influx script executable"
  file:
    path: "{{ vzdump2influx_script_source }}"
    mode: "0755"

- name: "Update vzdump2influx script with variables"
  include_tasks:
    file: "set-vzdump2influx-variables.yml"

- name: "Copy file only if it differs"
  copy:
    src: "{{ vzdump2influx_script_source }}"
    dest: "{{ vzdump2influx_script_destination }}"
    remote_src: true
    force: true

- name: "Add hook to backup job"
  lineinfile:
    path: "/etc/vzdump.conf"
    line: "script: {{ vzdump2influx_script_destination }}"
    state: "present"
  when: "add_hook_to_backup_job"
